/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargaRouteImport } from './routes/carga'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as VendedoresRouteImport } from './routes/vendedores'
import { Route as VentasRouteImport } from './routes/ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaRoute = CargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/vendedores': typeof VendedoresRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/vendedores': typeof VendedoresRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/vendedores': typeof VendedoresRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carga' | '/chat' | '/vendedores' | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carga' | '/chat' | '/vendedores' | '/ventas'
  id: '__root__' | '/' | '/carga' | '/chat' | '/vendedores' | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargaRoute: typeof CargaRoute
  ChatRoute: typeof ChatRoute
  VendedoresRoute: typeof VendedoresRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga': {
      id: '/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof CargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargaRoute: CargaRoute,
  ChatRoute: ChatRoute,
  VendedoresRoute: VendedoresRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
