/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargaRouteImport } from './routes/carga'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as VendedoresRouteImport } from './routes/vendedores'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClienteRouteImport } from './routes/clientes.$cliente'
import { Route as VendedoresIndexRouteImport } from './routes/vendedores.index'
import { Route as VendedoresVendedorRouteImport } from './routes/vendedores.$vendedor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaRoute = CargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClienteRoute = ClientesClienteRouteImport.update({
  id: '/$cliente',
  path: '/$cliente',
  getParentRoute: () => ClientesRoute,
} as any)
const VendedoresIndexRoute = VendedoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedoresRoute,
} as any)
const VendedoresVendedorRoute = VendedoresVendedorRouteImport.update({
  id: '/$vendedor',
  path: '/$vendedor',
  getParentRoute: () => VendedoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/vendedores': typeof VendedoresRouteWithChildren
  '/ventas': typeof VentasRoute
  '/clientes/$cliente': typeof ClientesClienteRoute
  '/vendedores/$vendedor': typeof VendedoresVendedorRoute
  '/clientes/': typeof ClientesIndexRoute
  '/vendedores/': typeof VendedoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/ventas': typeof VentasRoute
  '/clientes/$cliente': typeof ClientesClienteRoute
  '/vendedores/$vendedor': typeof VendedoresVendedorRoute
  '/clientes': typeof ClientesIndexRoute
  '/vendedores': typeof VendedoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/vendedores': typeof VendedoresRouteWithChildren
  '/ventas': typeof VentasRoute
  '/clientes/$cliente': typeof ClientesClienteRoute
  '/vendedores/$vendedor': typeof VendedoresVendedorRoute
  '/clientes/': typeof ClientesIndexRoute
  '/vendedores/': typeof VendedoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carga'
    | '/chat'
    | '/clientes'
    | '/vendedores'
    | '/ventas'
    | '/clientes/$cliente'
    | '/vendedores/$vendedor'
    | '/clientes/'
    | '/vendedores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carga'
    | '/chat'
    | '/ventas'
    | '/clientes/$cliente'
    | '/vendedores/$vendedor'
    | '/clientes'
    | '/vendedores'
  id:
    | '__root__'
    | '/'
    | '/carga'
    | '/chat'
    | '/clientes'
    | '/vendedores'
    | '/ventas'
    | '/clientes/$cliente'
    | '/vendedores/$vendedor'
    | '/clientes/'
    | '/vendedores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargaRoute: typeof CargaRoute
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  VendedoresRoute: typeof VendedoresRouteWithChildren
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga': {
      id: '/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof CargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$cliente': {
      id: '/clientes/$cliente'
      path: '/$cliente'
      fullPath: '/clientes/$cliente'
      preLoaderRoute: typeof ClientesClienteRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/vendedores/': {
      id: '/vendedores/'
      path: '/'
      fullPath: '/vendedores/'
      preLoaderRoute: typeof VendedoresIndexRouteImport
      parentRoute: typeof VendedoresRoute
    }
    '/vendedores/$vendedor': {
      id: '/vendedores/$vendedor'
      path: '/$vendedor'
      fullPath: '/vendedores/$vendedor'
      preLoaderRoute: typeof VendedoresVendedorRouteImport
      parentRoute: typeof VendedoresRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClienteRoute: typeof ClientesClienteRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteRoute: ClientesClienteRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface VendedoresRouteChildren {
  VendedoresVendedorRoute: typeof VendedoresVendedorRoute
  VendedoresIndexRoute: typeof VendedoresIndexRoute
}

const VendedoresRouteChildren: VendedoresRouteChildren = {
  VendedoresVendedorRoute: VendedoresVendedorRoute,
  VendedoresIndexRoute: VendedoresIndexRoute,
}

const VendedoresRouteWithChildren = VendedoresRoute._addFileChildren(
  VendedoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargaRoute: CargaRoute,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRouteWithChildren,
  VendedoresRoute: VendedoresRouteWithChildren,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
